{"uuid": "95823edf-ce30-4fec-bf79-6c9fe11fef07", "children": ["955126a0-85a1-40a3-8987-c9c991494369"], "befores": [{"name": "login_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception\nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (/Users/wayne/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.ts:86:11)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/wayne/.nvm/versions/node/v22.16.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (/Users/wayne/.nvm/versions/node/v22.16.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n", "trace": "  File \"/Users/wayne/Documents/work/auto-veloapp/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/Users/wayne/Documents/work/auto-veloapp/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/wayne/Documents/work/auto-veloapp/.venv/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/wayne/Documents/work/auto-veloapp/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/wayne/Documents/work/auto-veloapp/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/wayne/Documents/work/auto-veloapp/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/wayne/Documents/work/auto-veloapp/conftest.py\", line 28, in login_driver\n    driver.find_element(*sign_btn).click()\n  File \"/Users/wayne/Documents/work/auto-veloapp/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 922, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Users/wayne/Documents/work/auto-veloapp/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 454, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/wayne/Documents/work/auto-veloapp/.venv/lib/python3.10/site-packages/appium/webdriver/errorhandler.py\", line 125, in check_response\n    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\n"}, "start": 1752552539215, "stop": 1752552543479}], "start": 1752552539215, "stop": 1752552543516}